name: Pizza Delivery CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Замесить тесто
        run: echo "🫓 Замешиваю тесто на пиццу"
      
      - name: Нарезать ингредиенты
        run: echo "🍅 Нарезаю помидоры, грибы, перец"

  bake:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Выпекаю пиццу
        run: |
          echo "🔥 Пицца в духовке 10 минут"
          sleep 5
          echo "🍕 Пицца готова!"

  deliver:
    needs: bake
    runs-on: ubuntu-latest
    steps:
      - name: Упаковать пиццу
        run: echo "📦 Упаковываю пиццу в коробку"
      
      - name: Отправить курьеру
        run: echo "🛵 Курьер выехал!"
      
      - name: Доставить клиенту
        run: echo "🎉 Пицца доставлена! Приятного аппетита!"